package com.jmamoon;

import com.jmamoon.socialloansystem.model.*;
import com.jmamoon.socialloansystem.constants.Constants;

rule "person whose age is less than legal adult age"
    salience 200
    when
        loanRequest : LoanRequest();
        person : Person ( age < Constants.LEGAL_ADULT_AGE ) from loanRequest.getPerson();
    then
        loanRequest.addIssue("Person is too young");
end

rule "person whose age is more than maximum age"
    salience 200
    when
        loanRequest : LoanRequest();
        person : Person ( age > Constants.MAX_AGE ) from loanRequest.getPerson();
    then
        loanRequest.addIssue("Person is too old");
end

rule "person whose age is less or equal than breakpoint age"
    salience 100
    when
        loanRequest : LoanRequest();

        person : Person ( age <= Constants.BREAKPOINT_AGE ) from loanRequest.getPerson();
        personAffordablePayment : Double () from person.getAffordablePaymentPerMonth();

        property : Property (price > personAffordablePayment * Constants.MONTHS * Constants.YEARS_TO_PAY_YOUNG_PERSON ) from loanRequest.getProperty();

    then
        loanRequest.addIssue("Property is too expensive");
end

rule "person whose age is more than breakpoint age"
    salience 100
    when
        loanRequest : LoanRequest();

        person : Person ( age > Constants.BREAKPOINT_AGE ) from loanRequest.getPerson();
        personAffordablePayment : Double () from person.getAffordablePaymentPerMonth();

        property : Property (price > personAffordablePayment * Constants.MONTHS * Constants.YEARS_TO_PAY_OLD_PERSON ) from loanRequest.getProperty();

    then
        loanRequest.addIssue("Property is too expensive");
end
